package programon;
import javax.swing.JFrame;
/**
 *
 * @author RotiCanai
 */
public class Programon {
/**
 * This tester class is only used to open the game mode window
 * Do not edit this file
 * .
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { //A window to select game mode
        modeselect game = new modeselect(); //refers to modeselect class
        game.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //closes the window when X is pressed
        game.setLocationRelativeTo(null); //window opens at the center
        game.setSize(300,100); //window size
        game.setResizable(false); //cannot resize
        game.setVisible(true); //opens the window
        
    }
    
}
